#!/usr/bin/env python3
"""
Train AlphaQubit model from .npz files generated by generate_realistic_noise_data.py

This script bridges the gap between our realistic noise data generator
(which outputs .npz files) and the model training code.

Usage:
    python train_from_npz.py --data-dir pretrain_data/realistic --epochs 20 --npu
"""

import os
import sys
import math
import argparse
import json
from glob import glob
from pathlib import Path
from typing import List, Tuple, Optional

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, ConcatDataset
from tqdm import tqdm

# Add parent directory to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Import model components
from ai_models.model import (
    AlphaQubitDecoder,
    get_device,
    NPU_AVAILABLE,
)


class RealisticNpzDataset(Dataset):
    """Dataset that loads from .npz files created by generate_realistic_noise_data.py
    
    Expected .npz format:
        - detection_events: (N, num_detectors) or (N, R*S)
        - observables: (N,) or (N, 1) - logical error labels
        - distance, rounds, num_samples, basis (metadata)
    """
    
    def __init__(self, npz_path: str, basis_id: Optional[int] = None):
        """
        Args:
            npz_path: Path to .npz file
            basis_id: 0 for X basis, 1 for Z basis. If None, inferred from file.
        """
        data = np.load(npz_path, allow_pickle=True)
        
        # Get detection events
        if 'detection_events' in data:
            det_events = data['detection_events']
        elif 'data' in data:
            det_events = data['data']
        else:
            raise KeyError(f"No detection_events or data in {npz_path}")
        
        # Get labels (observables)
        if 'observables' in data:
            labels = data['observables']
        elif 'labels' in data:
            labels = data['labels']
        else:
            raise KeyError(f"No observables or labels in {npz_path}")
        
        # Get metadata
        distance = int(data.get('distance', 5))
        rounds = int(data.get('rounds', 25))
        basis = str(data.get('basis', 'z'))
        
        # Determine basis_id
        if basis_id is None:
            basis_id = 0 if basis.lower() == 'x' else 1
        
        N = det_events.shape[0]
        
        # Calculate stabilizers per round
        # For distance d, we have d^2 - 1 stabilizers
        num_stabilizers = distance * distance - 1
        
        # Reshape detection events to (N, R, S)
        if det_events.ndim == 2:
            # Shape is (N, total_detectors) where total = R * S
            total_det = det_events.shape[1]
            inferred_rounds = total_det // num_stabilizers
            if inferred_rounds * num_stabilizers != total_det:
                # Try different stabilizer count
                # For rotated surface code, stabilizers = d^2 - 1
                for d in [3, 5, 7]:
                    s = d * d - 1
                    if total_det % s == 0:
                        num_stabilizers = s
                        inferred_rounds = total_det // s
                        distance = d
                        break
            
            det_events = det_events.reshape(N, inferred_rounds, num_stabilizers)
            rounds = inferred_rounds
        
        # Add feature dimension: (N, R, S) -> (N, R, S, 1)
        x = det_events[:, :, :, np.newaxis].astype(np.float32)
        
        # Add basis channel: (N, R, S, 2)
        basis_feat = np.full((*x.shape[:-1], 1), basis_id, dtype=np.float32)
        x = np.concatenate([x, basis_feat], axis=-1)
        
        # Pad stabilizers to make S+1 a perfect square
        N, R, S, F = x.shape
        d = math.isqrt(S + 1)
        if d * d != S + 1:
            d += 1
            pad = d * d - 1 - S
            x = np.concatenate([x, np.zeros((N, R, pad, F), dtype=np.float32)], axis=2)
            S = d * d - 1
        
        self.X = torch.tensor(x, dtype=torch.float32)
        
        # Labels
        labels = labels.flatten().astype(np.float32)
        self.y = torch.tensor(labels, dtype=torch.float32)
        
        # Basis
        self.basis = torch.full((N,), basis_id, dtype=torch.long)
        
        # Final mask
        self.final_mask = torch.zeros(N, S, dtype=torch.long)
        for idx, (r, c) in enumerate([(i // d, i % d) for i in range(1, S + 1)]):
            self.final_mask[:, idx] = 1 if (r + c) % 2 == 0 else 2
        
        self.distance = distance
        self.rounds = R
        self.num_stabilizers = S
        
        print(f"  Loaded {npz_path}: N={N}, R={R}, S={S}, F={F}, d={distance}")
    
    def __len__(self):
        return len(self.y)
    
    def __getitem__(self, idx):
        return (self.X[idx], self.basis[idx], self.final_mask[idx]), self.y[idx]


def discover_npz_files(data_dir: str) -> List[str]:
    """Find all .npz files in data directory."""
    data_path = Path(data_dir)
    npz_files = []
    
    # Direct .npz files
    npz_files.extend(glob(str(data_path / "*.npz")))
    
    # In subdirectories
    npz_files.extend(glob(str(data_path / "*" / "*.npz")))
    npz_files.extend(glob(str(data_path / "realistic" / "*.npz")))
    
    return sorted(set(npz_files))


def build_dataset(npz_files: List[str]) -> Dataset:
    """Build combined dataset from multiple .npz files."""
    datasets = []
    for f in npz_files:
        try:
            ds = RealisticNpzDataset(f)
            datasets.append(ds)
        except Exception as e:
            print(f"  Warning: Could not load {f}: {e}")
    
    if not datasets:
        raise RuntimeError("No valid datasets found")
    
    if len(datasets) == 1:
        return datasets[0]
    return ConcatDataset(datasets)


def train(model, tr_loader, va_loader, epochs, lr, device, weight_decay=1e-4):
    """Training loop with validation."""
    
    # DataParallel for multiple devices
    if device.type == "npu" and hasattr(torch, "npu"):
        npu_count = getattr(torch.npu, "device_count", lambda: 1)()
        if npu_count > 1:
            print(f"Using {npu_count} NPUs!")
            model = nn.DataParallel(model)
    elif device.type == "cuda" and torch.cuda.device_count() > 1:
        print(f"Using {torch.cuda.device_count()} GPUs!")
        model = nn.DataParallel(model)
    
    model.to(device)
    
    # Optimizer with weight decay
    opt = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=epochs)
    
    # Loss with class weights for imbalanced data
    # Logical errors are typically rare (~5-15%), so weight the positive class higher
    pos_weight = torch.tensor([3.0]).to(device)  # Adjust based on error rate
    loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
    
    best_val_loss = float('inf')
    
    for ep in range(1, epochs + 1):
        # Training
        model.train()
        train_loss = 0
        train_correct = 0
        train_total = 0
        
        pbar = tqdm(tr_loader, desc=f"Epoch {ep}/{epochs}")
        for (xb, basis, mask), yb in pbar:
            xb = xb.to(device)
            basis = basis.to(device)
            mask = mask.to(device)
            yb = yb.to(device)
            
            opt.zero_grad()
            logits = model(xb, basis, mask)
            loss = loss_fn(logits, yb)
            loss.backward()
            
            # Gradient clipping
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step()
            
            train_loss += loss.item() * xb.size(0)
            preds = (torch.sigmoid(logits) > 0.5).float()
            train_correct += (preds == yb).sum().item()
            train_total += xb.size(0)
            
            pbar.set_postfix(loss=loss.item(), acc=train_correct/train_total)
        
        scheduler.step()
        
        train_loss /= train_total
        train_acc = train_correct / train_total
        
        # Validation
        model.eval()
        val_loss = 0
        val_correct = 0
        val_total = 0
        
        with torch.no_grad():
            for (xb, basis, mask), yb in va_loader:
                xb = xb.to(device)
                basis = basis.to(device)
                mask = mask.to(device)
                yb = yb.to(device)
                
                logits = model(xb, basis, mask)
                loss = loss_fn(logits, yb)
                
                val_loss += loss.item() * xb.size(0)
                preds = (torch.sigmoid(logits) > 0.5).float()
                val_correct += (preds == yb).sum().item()
                val_total += xb.size(0)
        
        val_loss /= val_total
        val_acc = val_correct / val_total
        
        print(f"Epoch {ep}: train_loss={train_loss:.4f}, train_acc={train_acc:.4f}, "
              f"val_loss={val_loss:.4f}, val_acc={val_acc:.4f}, lr={scheduler.get_last_lr()[0]:.2e}")
        
        # Save best model
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            if isinstance(model, nn.DataParallel):
                torch.save(model.module.state_dict(), "alphaqubit_best.pth")
            else:
                torch.save(model.state_dict(), "alphaqubit_best.pth")
            print(f"  Saved best model (val_loss={val_loss:.4f})")
    
    return model


def main():
    parser = argparse.ArgumentParser(description="Train AlphaQubit from .npz files")
    parser.add_argument("--data-dir", default="pretrain_data/realistic",
                        help="Directory containing .npz files")
    parser.add_argument("--epochs", type=int, default=20)
    parser.add_argument("--batch-size", type=int, default=64)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--npu", action="store_true", help="Use NPU")
    parser.add_argument("--hidden-dim", type=int, default=256)
    parser.add_argument("--num-layers", type=int, default=12)
    parser.add_argument("--num-heads", type=int, default=8)
    parser.add_argument("--checkpoint", default=None, help="Resume from checkpoint")
    args = parser.parse_args()
    
    torch.manual_seed(42)
    
    # Device
    if args.npu:
        try:
            import torch_npu
            if torch.npu.is_available():
                device = torch.device("npu:0")
                print(f"Using NPU: {torch.npu.get_device_name(0)}")
            else:
                print("NPU not available, falling back to CPU")
                device = torch.device("cpu")
        except ImportError:
            print("torch_npu not installed, falling back to CPU")
            device = torch.device("cpu")
    elif torch.cuda.is_available():
        device = torch.device("cuda:0")
        print(f"Using CUDA: {torch.cuda.get_device_name(0)}")
    else:
        device = torch.device("cpu")
        print("Using CPU")
    
    # Find data files
    print(f"\nSearching for .npz files in {args.data_dir}...")
    npz_files = discover_npz_files(args.data_dir)
    
    if not npz_files:
        print(f"ERROR: No .npz files found in {args.data_dir}")
        print("Please run: python generate_realistic_noise_data.py --mode pretrain ...")
        sys.exit(1)
    
    print(f"Found {len(npz_files)} .npz files")
    
    # Build dataset
    print("\nLoading datasets...")
    dataset = build_dataset(npz_files)
    print(f"Total samples: {len(dataset)}")
    
    # Split into train/val
    n = len(dataset)
    indices = torch.randperm(n)
    split = int(0.9 * n)
    
    train_ds = torch.utils.data.Subset(dataset, indices[:split])
    val_ds = torch.utils.data.Subset(dataset, indices[split:])
    
    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True, 
                              num_workers=0, pin_memory=True)
    val_loader = DataLoader(val_ds, batch_size=args.batch_size, shuffle=False,
                           num_workers=0, pin_memory=True)
    
    print(f"Train samples: {len(train_ds)}, Val samples: {len(val_ds)}")
    
    # Get dimensions from first sample
    (x0, _, _), _ = dataset[0]
    R, S, F = x0.shape
    d = int(math.sqrt(S + 1))
    grid_size = d - 1
    
    print(f"\nModel config: R={R}, S={S}, F={F}, grid={d}x{d}")
    
    # Create model
    model = AlphaQubitDecoder(
        num_features=F,
        hidden_dim=args.hidden_dim,
        num_stabilizers=S,
        grid_size=grid_size,
        num_heads=args.num_heads,
        num_layers=args.num_layers,
    )
    
    # Count parameters
    n_params = sum(p.numel() for p in model.parameters())
    print(f"Model parameters: {n_params:,}")
    
    # Load checkpoint if provided
    if args.checkpoint and os.path.exists(args.checkpoint):
        try:
            state_dict = torch.load(args.checkpoint, map_location="cpu")
            model.load_state_dict(state_dict)
            print(f"Loaded checkpoint: {args.checkpoint}")
        except Exception as e:
            print(f"Warning: Could not load checkpoint: {e}")
    
    # Train
    print("\nStarting training...")
    model = train(model, train_loader, val_loader, args.epochs, args.lr, device)
    
    # Save final model
    final_path = "alphaqubit_final.pth"
    if isinstance(model, nn.DataParallel):
        torch.save(model.module.state_dict(), final_path)
    else:
        torch.save(model.state_dict(), final_path)
    print(f"\nSaved final model: {final_path}")


if __name__ == "__main__":
    main()
